/**
 * Ideas board stylesheet (plain CSS, injected once per page) and the class
 * map consumed by the sidebar core and the React board. Scoped by the
 * plugin's own data attributes so nothing leaks into the rest of the GUI;
 * colors ride the dsh --dsw-* tokens so the board follows the active theme
 * (light/dark and skins).
 */
/** Class map consumed by the sidebar core and the board JSX. */
export declare const classes: {
    readonly entry: "dsh-ideas-entry";
    readonly entryIcon: "dsh-ideas-entry-icon";
    readonly entryLabel: "dsh-ideas-entry-label";
    readonly boardView: "dsh-ideas-board-view";
    readonly board: "dsh-ideas-board";
    readonly boardHeader: "dsh-ideas-board-header";
    readonly boardTitle: "dsh-ideas-board-title";
    readonly backButton: "dsh-ideas-back-button";
    readonly detailMeta: "dsh-ideas-detail-meta";
    readonly search: "dsh-ideas-search";
    readonly workspaceSelect: "dsh-ideas-workspace-select";
    readonly mdToggle: "dsh-ideas-md-toggle";
    readonly mdToggleButton: "dsh-ideas-md-toggle-button";
    readonly mdToggleActive: "dsh-ideas-md-toggle-active";
    readonly primaryButton: "dsh-ideas-primary-button";
    readonly ghostButton: "dsh-ideas-ghost-button";
    readonly error: "dsh-ideas-error";
    readonly columns: "dsh-ideas-columns";
    readonly column: "dsh-ideas-column";
    readonly columnHeader: "dsh-ideas-column-header";
    readonly columnTitle: "dsh-ideas-column-title";
    readonly columnCount: "dsh-ideas-column-count";
    readonly quickAdd: "dsh-ideas-quick-add";
    readonly columnBody: "dsh-ideas-column-body";
    readonly empty: "dsh-ideas-empty";
    readonly card: "dsh-ideas-card";
    readonly cardHeader: "dsh-ideas-card-header";
    readonly cardTitle: "dsh-ideas-card-title";
    readonly cardNumber: "dsh-ideas-card-number";
    readonly cardGrip: "dsh-ideas-card-grip";
    readonly cardBody: "dsh-ideas-card-body";
    readonly bodyClickable: "dsh-ideas-body-clickable";
    readonly markdownBody: "dsh-ideas-markdown-body";
    readonly cardMeta: "dsh-ideas-card-meta";
    readonly tag: "dsh-ideas-tag";
    readonly score: "dsh-ideas-score";
    readonly workspaceChip: "dsh-ideas-workspace-chip";
    readonly updated: "dsh-ideas-updated";
    readonly overlay: "dsh-ideas-overlay";
    readonly modal: "dsh-ideas-modal";
    readonly modalTitle: "dsh-ideas-modal-title";
    readonly field: "dsh-ideas-field";
    readonly fieldRow: "dsh-ideas-field-row";
    readonly fieldRowBetween: "dsh-ideas-field-row-between";
    readonly modelRow: "dsh-ideas-model-row";
    readonly rankLevelRow: "dsh-ideas-rank-level-row";
    readonly fieldLabel: "dsh-ideas-field-label";
    readonly input: "dsh-ideas-input";
    readonly textarea: "dsh-ideas-textarea";
    readonly bodyTextarea: "dsh-ideas-body-textarea";
    readonly select: "dsh-ideas-select";
    readonly preview: "dsh-ideas-preview";
    readonly modalActions: "dsh-ideas-modal-actions";
    readonly editActions: "dsh-ideas-edit-actions";
    readonly tagFilterRow: "dsh-ideas-tag-filter-row";
    readonly tagFilterHeader: "dsh-ideas-tag-filter-header";
    readonly tagFilterLabel: "dsh-ideas-tag-filter-label";
    readonly tagFilterSearch: "dsh-ideas-tag-filter-search";
    readonly tagFilterChips: "dsh-ideas-tag-filter-chips";
    readonly tagFilterNoMatch: "dsh-ideas-tag-filter-no-match";
    readonly settingsSection: "dsh-ideas-settings-section";
    readonly settingsTitle: "dsh-ideas-settings-title";
    readonly settingsIntro: "dsh-ideas-settings-intro";
    readonly settingsCard: "dsh-ideas-settings-card";
    readonly settingsGroup: "dsh-ideas-settings-group";
    readonly settingsRow: "dsh-ideas-settings-row";
    readonly settingsRowText: "dsh-ideas-settings-row-text";
    readonly settingsRowTitle: "dsh-ideas-settings-row-title";
    readonly settingsRowDesc: "dsh-ideas-settings-row-desc";
    readonly settingsNumber: "dsh-ideas-settings-number";
    readonly settingsSelect: "dsh-ideas-settings-select";
    readonly settingsCheck: "dsh-ideas-settings-check";
    readonly settingsError: "dsh-ideas-settings-error";
    readonly settingsNote: "dsh-ideas-settings-note";
    readonly filterChip: "dsh-ideas-filter-chip";
    readonly filterChipActive: "dsh-ideas-filter-chip-active";
    readonly dragHint: "dsh-ideas-drag-hint";
    readonly cardWrapper: "dsh-ideas-card-wrapper";
    readonly cardActions: "dsh-ideas-card-actions";
    readonly actionButton: "dsh-ideas-action-button";
    readonly dangerButton: "dsh-ideas-danger-button";
    readonly confirmLabel: "dsh-ideas-confirm-label";
    readonly tabs: "dsh-ideas-tabs";
    readonly tab: "dsh-ideas-tab";
    readonly tabActive: "dsh-ideas-tab-active";
    readonly priorities: "dsh-ideas-priorities";
    readonly prioritiesHint: "dsh-ideas-priorities-hint";
    readonly prioritiesGroup: "dsh-ideas-priorities-group";
    readonly prioritiesGroupTitle: "dsh-ideas-priorities-group-title";
    readonly prioritiesList: "dsh-ideas-priorities-list";
    readonly prioritiesRow: "dsh-ideas-priorities-row";
    readonly prioritiesRank: "dsh-ideas-priorities-rank";
    readonly prioritiesGrow: "dsh-ideas-priorities-grow";
    readonly prioritiesTitle: "dsh-ideas-priorities-title";
    readonly prioritiesRationale: "dsh-ideas-priorities-rationale";
    readonly prioritiesRationaleLabel: "dsh-ideas-priorities-rationale-label";
    readonly prioritiesRationaleText: "dsh-ideas-priorities-rationale-text";
    readonly prioritiesActions: "dsh-ideas-priorities-actions";
    readonly prioritiesMove: "dsh-ideas-priorities-move";
    readonly deliveredStamp: "dsh-ideas-delivered-stamp";
    readonly deliveredBadge: "dsh-ideas-delivered-badge";
    readonly archivedStamp: "dsh-ideas-archived-stamp";
    readonly reviewBadge: "dsh-ideas-review-badge";
    readonly followUpBadge: "dsh-ideas-followup-badge";
    readonly tabCount: "dsh-ideas-tab-count";
    readonly scoreIcon: "dsh-ideas-score-icon";
    readonly fieldHint: "dsh-ideas-field-hint";
};
/** Inject the stylesheet once per page (idempotent, plugin-owned tag). */
export declare function ensureIdeasStyle(): void;
