/**
 * Unidirectional ledger -> markdown export for the /api/ideas `export` verb.
 *
 * The markdown is a *view* of the Host ledger: it is generated on demand and
 * never parsed back (the ledger is the source of truth; bulk `import` of a
 * capture document moves *into* the ledger, never from a markdown file). The
 * format below is pinned by the golden tests — change consciously.
 */

import type { IdeaRecord } from './core/ideas.ts'

/** ISO-8601 UTC instant (stable across the platform). */
function iso(ms: number): string {
  return new Date(ms).toISOString()
}

function bullet(label: string, value: string): string {
  return `- ${label}: ${value}`
}

/** Render one idea as a markdown section. */
export function ideaToMarkdown(idea: IdeaRecord): string {
  const lines: string[] = [`## ${idea.title}`, '']
  lines.push(bullet('id', `\`${idea.id}\``))
  lines.push(bullet('status', idea.status))
  if (idea.ideaNumber !== undefined) lines.push(bullet('number', `#${idea.ideaNumber}`))
  if (idea.tags !== undefined && idea.tags.length > 0) {
    lines.push(bullet('tags', idea.tags.map(tag => `\`${tag.name}\``).join(', ')))
  }
  const scores: string[] = []
  if (idea.value !== undefined) scores.push(`value: ${idea.value}`)
  if (idea.effort !== undefined) scores.push(`effort: ${idea.effort}`)
  if (scores.length > 0) lines.push(bullet('scores', scores.join(' · ')))
  if (idea.rank !== undefined) lines.push(bullet('rank', String(idea.rank)))
  if (idea.workspaceId !== undefined) lines.push(bullet('workspace', `\`${idea.workspaceId}\``))
  if (idea.rationale !== undefined) lines.push(bullet('rationale', idea.rationale))
  if (idea.decision !== undefined) lines.push(bullet('decision', idea.decision))
  if (idea.followUpOfId !== undefined) lines.push(bullet('follow-up of', `\`${idea.followUpOfId}\``))
  lines.push(bullet('created', iso(idea.createdAt)))
  lines.push(bullet('updated', iso(idea.updatedAt)))
  if (idea.deliveredAt !== undefined) lines.push(bullet('delivered', iso(idea.deliveredAt)))
  if (idea.archivedAt !== undefined) lines.push(bullet('archived', iso(idea.archivedAt)))
  if (idea.body.trim() !== '') {
    lines.push('', idea.body.trim(), '')
  }
  lines.push('')
  return lines.join('\n')
}

/**
 * Generate the two export documents.
 * @param ideas - the full ledger ideas (filtered by the caller when a
 *   workspace is requested).
 * @param title - document heading (e.g. "IDEAS" / "IDEAS-ARCHIVE").
 * @param noun - singular labelling used in the empty state.
 */
export function ideasToMarkdown(ideas: readonly IdeaRecord[], title: string, noun: string): string {
  const lines: string[] = [
    `# ${title}`,
    '',
    `> Generated by dsh-plugin-ideas-manager at ${iso(Date.now())}. Unidirectional: edit the ledger, never this file.`,
    '',
  ]
  if (ideas.length === 0) {
    lines.push(`_No ${noun} yet._`, '')
    return lines.join('\n')
  }
  for (const idea of ideas) {
    lines.push(ideaToMarkdown(idea))
  }
  return lines.join('\n')
}

/** Export payload returned by the `export` action. */
export interface IdeasExport {
  ideasMd: string
  archiveMd: string
}

/**
 * Build the export for a ledger (optionally filtered to one workspace).
 * Open + under-review ideas go to the main document (under review = task
 * done, human acceptance pending — still active work, not delivered);
 * archived/declined ideas go to the archive document.
 */
export function buildIdeasExport(
  ideas: readonly IdeaRecord[],
  workspaceId: string | undefined,
): IdeasExport {
  const filter = workspaceId === undefined
    ? undefined
    : (idea: IdeaRecord): boolean => idea.workspaceId === workspaceId
  const active = ideas.filter(idea => (idea.status === 'open' || idea.status === 'underReview') && (filter === undefined || filter(idea)))
  const closed = ideas.filter(idea => (idea.status === 'archived' || idea.status === 'declined') && (filter === undefined || filter(idea)))
  return {
    ideasMd: ideasToMarkdown(active, 'IDEAS', 'open ideas'),
    archiveMd: ideasToMarkdown(closed, 'IDEAS-ARCHIVE', 'archived ideas'),
  }
}