/**
 * Unidirectional ledger -> markdown export for the /api/ideas `export` verb.
 *
 * The markdown is a *view* of the Host ledger: it is generated on demand and
 * never parsed back (the ledger is the source of truth; bulk `import` of a
 * capture document moves *into* the ledger, never from a markdown file). The
 * format below is pinned by the golden tests — change consciously.
 *
 * The activity log IS carried, as a bounded `**Activity**` block
 * per idea. Decision and rationale: these two documents are the only portable
 * artefact the plugin produces, and "why was this declined?" is unanswerable
 * from a last-state record. The JSON round-trip (`GET /state` → `import`) also
 * carries it, so nothing is lost either way — this block exists for the READER
 * of the exported file, not for a parser.
 */

import type { IdeaRecord } from './core/ideas.ts'

/** ISO-8601 UTC instant (stable across the platform). */
function iso(ms: number): string {
  return new Date(ms).toISOString()
}

function bullet(label: string, value: string): string {
  return `- ${label}: ${value}`
}

/** Render one idea as a markdown section. */
export function ideaToMarkdown(idea: IdeaRecord): string {
  const lines: string[] = [`## ${idea.title}`, '']
  lines.push(bullet('id', `\`${idea.id}\``))
  lines.push(bullet('status', idea.status))
  if (idea.ideaNumber !== undefined) lines.push(bullet('number', `#${idea.ideaNumber}`))
  if (idea.tags !== undefined && idea.tags.length > 0) {
    lines.push(bullet('tags', idea.tags.map(tag => `\`${tag.name}\``).join(', ')))
  }
  const scores: string[] = []
  if (idea.value !== undefined) scores.push(`value: ${idea.value}`)
  if (idea.effort !== undefined) scores.push(`effort: ${idea.effort}`)
  if (scores.length > 0) lines.push(bullet('scores', scores.join(' · ')))
  if (idea.rank !== undefined) lines.push(bullet('rank', String(idea.rank)))
  if (idea.workspaceId !== undefined) lines.push(bullet('workspace', `\`${idea.workspaceId}\``))
  if (idea.rationale !== undefined) lines.push(bullet('rationale', idea.rationale))
  if (idea.decision !== undefined) lines.push(bullet('decision', idea.decision))
  if (idea.followUpOfId !== undefined) lines.push(bullet('follow-up of', `\`${idea.followUpOfId}\``))
  // Relations, carried like any other stored fact. The stored
  // direction is printed: `relates to` is symmetric by construction so both
  // rows carry the edge, and `blocks` is one-directional with its `blocked by`
  // side living on the other row — so a reader follows the id the same way the
  // ledger does. The markdown is never parsed back, so this is for the human
  // reading the archive, exactly like the Activity block below.
  if (idea.relatesTo !== undefined && idea.relatesTo.length > 0) {
    lines.push(bullet('relates to', idea.relatesTo.map(id => `\`${id}\``).join(', ')))
  }
  if (idea.blocks !== undefined && idea.blocks.length > 0) {
    lines.push(bullet('blocks', idea.blocks.map(id => `\`${id}\``).join(', ')))
  }
  lines.push(bullet('created', iso(idea.createdAt)))
  lines.push(bullet('updated', iso(idea.updatedAt)))
  if (idea.deliveredAt !== undefined) lines.push(bullet('delivered', iso(idea.deliveredAt)))
  if (idea.archivedAt !== undefined) lines.push(bullet('archived', iso(idea.archivedAt)))
  // Delivery note: what the last finished run said, verbatim.
  // Carried like any other stored fact because the archive document is read by
  // humans AND by agents deciding whether an idea is still relevant.
  if (idea.deliveryNote !== undefined) lines.push(bullet('delivery note', idea.deliveryNote))
  // Activity log. Decision: the markdown export CARRIES it. The two
  // export documents are the only portable artefact this plugin produces, and
  // the question a re-reader of an archive section actually asks — "declined on
  // 2026-09-20 because …?" — is unanswerable from the last state alone. It costs
  // one bounded line per entry (at most IDEA_EVENT_LIMIT of them) and the log is
  // never parsed back: `import` round-trips the JSON, not this document.
  if (idea.events !== undefined && idea.events.length > 0) {
    lines.push('', '**Activity**', '')
    for (const entry of idea.events) {
      lines.push(`- ${iso(entry.at)} · ${entry.verb} · ${entry.actor} — ${entry.summary}`)
    }
    lines.push('')
  }
  if (idea.body.trim() !== '') {
    lines.push('', idea.body.trim(), '')
  }
  lines.push('')
  return lines.join('\n')
}

/**
 * Generate the two export documents.
 * @param ideas - the full ledger ideas (filtered by the caller when a
 *   workspace is requested).
 * @param title - document heading (e.g. "IDEAS" / "IDEAS-ARCHIVE").
 * @param noun - singular labelling used in the empty state.
 */
export function ideasToMarkdown(ideas: readonly IdeaRecord[], title: string, noun: string): string {
  const lines: string[] = [
    `# ${title}`,
    '',
    `> Generated by dsh-plugin-ideas-manager at ${iso(Date.now())}. Unidirectional: edit the ledger, never this file.`,
    '',
  ]
  if (ideas.length === 0) {
    lines.push(`_No ${noun} yet._`, '')
    return lines.join('\n')
  }
  for (const idea of ideas) {
    lines.push(ideaToMarkdown(idea))
  }
  return lines.join('\n')
}

/** Export payload returned by the `export` action. */
export interface IdeasExport {
  ideasMd: string
  archiveMd: string
}

/**
 * Build the export for a ledger (optionally filtered to one workspace).
 * Open + under-review ideas go to the main document (under review = task
 * done, human acceptance pending — still active work, not delivered);
 * archived/declined ideas go to the archive document.
 */
export function buildIdeasExport(
  ideas: readonly IdeaRecord[],
  workspaceId: string | undefined,
): IdeasExport {
  const filter = workspaceId === undefined
    ? undefined
    : (idea: IdeaRecord): boolean => idea.workspaceId === workspaceId
  const active = ideas.filter(idea => (idea.status === 'open' || idea.status === 'underReview') && (filter === undefined || filter(idea)))
  const closed = ideas.filter(idea => (idea.status === 'archived' || idea.status === 'declined') && (filter === undefined || filter(idea)))
  return {
    ideasMd: ideasToMarkdown(active, 'IDEAS', 'open ideas'),
    archiveMd: ideasToMarkdown(closed, 'IDEAS-ARCHIVE', 'archived ideas'),
  }
}